/**
 * Stable machine-readable reason codes for compatibility results.
 *
 * Reason codes are part of the resolver contract: they may be persisted
 * (rejection-reason persistence is a documented future item) and consumed
 * by explanation generation, so they must not be renamed casually.
 */
const REASON_CODES = Object.freeze({
  // CPU <-> motherboard
  CPU_SOCKET_MISMATCH: 'CPU_SOCKET_MISMATCH',
  CPU_SOCKET_UNKNOWN: 'CPU_SOCKET_UNKNOWN',
  CPU_MOTHERBOARD_SUPPORT_FAIL: 'CPU_MOTHERBOARD_SUPPORT_FAIL',
  CPU_MOTHERBOARD_SUPPORT_UNKNOWN: 'CPU_MOTHERBOARD_SUPPORT_UNKNOWN',
  CPU_MOTHERBOARD_CONDITIONAL_UNVERIFIABLE:
    'CPU_MOTHERBOARD_CONDITIONAL_UNVERIFIABLE',

  // Cooler <-> socket
  COOLER_SOCKET_MISMATCH: 'COOLER_SOCKET_MISMATCH',
  COOLER_SOCKET_SUPPORT_UNKNOWN: 'COOLER_SOCKET_SUPPORT_UNKNOWN',

  // Case <-> motherboard form factor
  CASE_FORM_FACTOR_MISMATCH: 'CASE_FORM_FACTOR_MISMATCH',
  CASE_FORM_FACTOR_UNKNOWN: 'CASE_FORM_FACTOR_UNKNOWN',

  // Case <-> radiator
  RADIATOR_UNSUPPORTED: 'RADIATOR_UNSUPPORTED',
  RADIATOR_SUPPORT_UNKNOWN: 'RADIATOR_SUPPORT_UNKNOWN',

  // Platform <-> RAM memory type
  PLATFORM_MEMORY_TYPE_UNSUPPORTED: 'PLATFORM_MEMORY_TYPE_UNSUPPORTED',
  PLATFORM_MEMORY_SUPPORT_UNKNOWN: 'PLATFORM_MEMORY_SUPPORT_UNKNOWN',

  // Motherboard <-> RAM memory type
  MOTHERBOARD_MEMORY_TYPE_MISMATCH: 'MOTHERBOARD_MEMORY_TYPE_MISMATCH',
  MOTHERBOARD_MEMORY_SUPPORT_UNKNOWN: 'MOTHERBOARD_MEMORY_SUPPORT_UNKNOWN',

  // GPU <-> case (derived from numeric specs)
  GPU_TOO_LONG: 'GPU_TOO_LONG',
  GPU_TOO_THICK: 'GPU_TOO_THICK',
  GPU_DIMENSIONS_UNKNOWN: 'GPU_DIMENSIONS_UNKNOWN',

  // GPU <-> PSU (derived from numeric specs)
  GPU_PSU_WATTAGE_INSUFFICIENT: 'GPU_PSU_WATTAGE_INSUFFICIENT',
  GPU_PSU_WATTAGE_UNKNOWN: 'GPU_PSU_WATTAGE_UNKNOWN',
  GPU_PSU_CONNECTOR_UNAVAILABLE: 'GPU_PSU_CONNECTOR_UNAVAILABLE',
  GPU_PSU_CONNECTOR_UNKNOWN: 'GPU_PSU_CONNECTOR_UNKNOWN',
});

module.exports = { REASON_CODES };
